name: Starting Mirroring

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  DURL: https://download.wetransfer.com//us2/893b7130abbfeada66528b04fbdffaab20200627110902/ba4e59df6f9902c03ea64ec7ea05595318e1eda6/MIUI-AB-10-20200627-ruigsi.7z?cf=y&token=eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1OTMyNTc1MzYsInVuaXF1ZSI6Ijg5M2I3MTMwYWJiZmVhZGE2NjUyOGIwNGZiZGZmYWFiMjAyMDA2MjcxMTA5MDIiLCJmaWxlbmFtZSI6Ik1JVUktQUItMTAtMjAyMDA2MjctcnVpZ3NpLjd6IiwiaG90IjpmYWxzZSwid2F5YmlsbF91cmwiOiJodHRwOi8vcHJvZHVjdGlvbi5iYWNrZW5kLnNlcnZpY2UudXMtZWFzdC0xLnd0OjkyOTIvd2F5YmlsbC92MS9zYXJrYXIvMmNkYTZlZGI5ZjkxZjk1ODFhNTllYjAyNTdhYzAzNmFhMDY1OTJmMmFjNjIxZjhiODUyOTAxYmZiYzU1ZDY1YWI4ZGU4Y2E2MWU2OWFiMDhiZmMxNzIiLCJmaW5nZXJwcmludCI6ImJhNGU1OWRmNmY5OTAyYzAzZWE2NGVjN2VhMDU1OTUzMThlMWVkYTYiLCJjYWxsYmFjayI6IntcImZvcm1kYXRhXCI6e1wiYWN0aW9uXCI6XCJodHRwOi8vcHJvZHVjdGlvbi5mcm9udGVuZC5zZXJ2aWNlLmV1LXdlc3QtMS53dDozMDAwL3dlYmhvb2tzL2JhY2tlbmRcIn0sXCJmb3JtXCI6e1widHJhbnNmZXJfaWRcIjpcIjg5M2I3MTMwYWJiZmVhZGE2NjUyOGIwNGZiZGZmYWFiMjAyMDA2MjcxMTA5MDJcIixcImRvd25sb2FkX2lkXCI6OTYyMjgyNTMyOH19In0.T8kpQQQ_w2MTrk59bBNdHmCfTMF2JWE-fYtu_ncaD1w
  TZ: Asia/Kolkata
  MIR: bit
  EXT: zip
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master      

       - name: Clean Up
         run: |
           docker rmi `docker images -q`
           sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
           sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
           sudo -E apt-get update
           sudo -E apt-get -y autoremove --purge
           sudo -E apt-get clean 
       - name: Initializing environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install aria2 curl wget
       - name: Download time
         run: |
            aria2c $DURL
       - name: Download transfer
         run: |
            curl -sL https://git.io/file-transfer | sh
       - name: its upload time
         run: |
            ./transfer $MIR *.$EXT
